# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculating binned matrix product
#'
#' This function calculates the matrix product using Algorithm 3 of Zheyuan Li, Simon N. Wood: "Faster
#' model matrix crossproducts for large generalized linear models with discretized covariates". The idea
#' is to compute just on the unique rows of X by also using an index vector to map to the original matrix.
#' The algorithm implemented here is a small adaption of the original algorithm. Instead of calculating $XW$
#' which again, needs to be transposed, we directly calculate $X^TW$ to avoid another transposing step.
#'
#' @param X [\code{arma::mat}]\cr
#'   Matrix X.
#' @param k [\code{arma::uvec}]\cr
#'   Index vector for mapping to original matrix $X_o(i,) = X(k(i),.)$.
#' @param w [\code{arma::vec}]\cr
#'   Vector of weights that are accumulated.
#' @return \code{arma::mat} Matrix Product $X^TWX$.
#' @examples
#'
#' @export
binnedMatMult <- function(X, k, w) {
    .Call(`_compboostBinning_binnedMatMult`, X, k, w)
}

binnedMatMultResponse <- function(X, y, k, w) {
    .Call(`_compboostBinning_binnedMatMultResponse`, X, y, k, w)
}

